title: Hou Pingqing's Homepage
page-top-title: Hou Pingqing
top-section-bg-text: Internet of Things Engineering
home-subtitle: Hou Pingqing &ensp;|&ensp;侯平庆
copyright-text: '&copy; Hou Pingqing 2022-2026. All Rights Reserved.'
